### ISSUE TITLE
Failed to EGL with glad.

### ISSUE THREAD

**Issue by half-potato** [StanfordVL/GibsonEnv#76]
```
pybullet build time: Mar 27 2019 11:14:22
pygame 1.9.4
Hello from the pygame community. https://www.pygame.org/contribute.html
/home/loopclosure/GibsonEnv/random_views.yaml
Processing the data:
Total 1 scenes 0 train 1 test
Indexing
  0%|                                                                  | 0/1 [00:00<?, ?it/s]failed to EGL with glad.
100%|██████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  6.21it/s]
100%|██████████████████████████████████████████████████████| 190/190 [00:19<00:00,  9.74it/s]
Episode: steps:0 score:0
Episode count: 0
```
I have EGL installed though. 
```
(gibson) loopclosure/GibsonEnv [ ldconfig -p | grep egl                   master * ] 1:28 PM
        libwayland-egl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libwayland-egl.so.1
        libwayland-egl.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libwayland-egl.so
        libnvidia-eglcore.so.396.54 (libc6,x86-64) => /usr/lib/nvidia-396/libnvidia-eglcore.so.396.54
        libnvidia-eglcore.so.396.54 (libc6) => /usr/lib32/nvidia-396/libnvidia-eglcore.so.396.54
        libnvidia-egl-wayland.so.1 (libc6,x86-64) => /usr/lib/nvidia-396/libnvidia-egl-wayland.so.1
        libhybris-eglplatformcommon.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libhybris-eglplatformcommon.so.1
        libgegl-0.3.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgegl-0.3.so.0
        libgegl-sc-0.3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgegl-sc-0.3.so
        libgegl-npd-0.3.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libgegl-npd-0.3.so
(gibson) loopclosure/GibsonEnv [ vim examples/configs/play/play_husky_camera.yaml
```
And I'm running it headless.
```
envname: TurtlebotNavigateEnv
#model_id: stadium
model_id: space7
target_orn: [0, 0, 1.57]
target_pos: [-14.3, 45.07, 0.5]
initial_orn: [0, 0, 4.71]
initial_pos: [-14.3, 5, 1.2]
fov: 1.57
is_discrete: true

use_filler: true
display_ui: false
show_diagnostics: true
ui_num: 2
ui_components: [RGB_FILLED, DEPTH]
random:
  random_initial_pose : false
  random_target_pose : false
  random_init_x_range: [-0.1, 0.1]
  random_init_y_range: [-0.1, 0.1]
  random_init_z_range: [-0.1, 0.1]
  random_init_rot_range: [-0.1, 0.1]

#output: [nonviz_sensor]
output: [nonviz_sensor, rgb_filled, depth]
resolution: 256

speed:
  timestep: 0.00417
  frameskip: 1

mode: headless #gui|headless
verbose: true
```
